"use client";
import React from 'react';
import Link from 'next/link';

const TermsAndConditions = () => {
  return (
    
    <main id="maincontent" className="page-main">
        <style>{`
             body {
          background: radial-gradient(circle at top left, rgba(255, 235, 180, 0.3) 0%, rgba(255, 235, 180, 0.3) 0%, rgb(255, 255, 255) 30%);
        }
      `}</style>
      {/* Hero Section */}
      <section className="network-hero-section">
        <div className="container">
          <div className="mb-2">
            <img 
              className="img-fluid" 
              src="/images/book.png" 
              alt="Terms Icon" 
            />
          </div>
          <div className="network-headeing">
            <p>Terms and Conditions</p>
          </div>
          <div className="sub-heading">
            <p className="title-one">Terms and Conditions</p>
          </div>
        </div>
      </section>

      <section className="network-acordian">
        {/* Breadcrumbs */}
        <div className="container">
          <div className="breadcrumbs">
            <div>
              <img 
                src="/images/breadcrumb-arrow.png" 
                alt="arrow" 
              />
            </div>
            <div>
              <Link href="/">Home</Link> <span>/</span>
              <span>Terms and Conditions</span>
            </div>
          </div>
        </div>

        <div className="container">
                                                <div className="MB-32">
                                                    <p className="m-0 mt-3 text-primary fs-16">Please note that your use of and access to our services are subject to the following terms; if you do not agree to all of the following, you may not use or access the services in any manner.</p>
                                                    <p className="m-0 mt-3 text-primary fs-16">Healthy Business Group, through its Solo Health Collective website (the “Site”), offers customers products and services (the “Services”). These Standard Terms and Conditions (“T&Cs”) are made by and between Healthy Business Group, a New York limited liability company (“Solo Health Collective”, “Company”) and any person, dependent, entity, representative, employee or agent who uses or accesses the Services (“User”).</p>
                                                    <p className="m-0 mt-3 text-primary fs-16">Use of the Site and the Services are conditional upon User’s full compliance with these T&Cs; all applicable laws, rules, and regulations; and any supplemental terms referenced herein or which Solo Health Collective may present User with for review and acceptance at the time User subscribes to such Service (“Service Terms”). The Service Terms shall be incorporated into and form a part of these T&Cs. If the terms herein conflict with any Service Terms, the Service Terms will govern the matters.</p>
                                                </div>
                                                <div className="MB-32">
                                                    <h2 className="m-0 mb-1 text-primary fs-24 fw-bold">Terms and Conditions</h2>
                                                    <p className="m-0 mt-3 text-primary fs-16">We may collect the following information:</p>
                                                    <ul>
                                                        <li className="text-primary"><strong>User Accounts; Privacy Policy.</strong> To use the Site, User may be required to create an account and password. To create an account, User must be at least 18 years old and must provide Solo Health Collective with truthful and accurate information during the account creation process. User acknowledges and agrees that Solo Health Collective may collect, use, and disclose User’s information, including personal information, according to the company’s Privacy Policy.</li>
                                                        <li className="text-primary">
                                                            <p className="text-primary"><strong>User Responsibilities.</strong> Any actions taken within Accounts that User has access to will be deemed authorized by User, regardless of the User’s knowledge of such actions (the “Authorized Actions”). Authorized Actions include but are not limited to (i) actions taken by User, an Account Administrator, or an authorized representative of User (an “Authorized Representative”), and (ii) actions that User, an Account Administrator, or an Authorized Representative (or anyone that Solo Health Collective reasonably believes to be User, an Account Administrator, or an Authorized Representative) directs or instructs Solo Health Collective to take on its behalf. Solo Health Collective has no responsibility to confirm the authority of any Account Administrator or Authorized Representative.</p>
                                                            <p className="text-primary">In addition, User is solely responsible for following instructions that Solo Health Collective provides to User concerning the Services and maintaining applicable accounts with providers of Third-Party Services (as defined below) utilized by User.</p>
                                                            <p className="text-primary">User is further responsible for providing Solo Health Collective with the information required for Solo Health Collective to perform the Services. User represents and warrants to Solo Health Collective that for any information that User shares with Solo Health Collective, whether directly or through a representative, User will have the authority to share such information. User is also responsible for reviewing any information, documents or materials (collectively, the “Materials”) made available for User’s review by Solo Health Collective. User is responsible for and shall maintain the accuracy and completeness of such information and Materials on an ongoing basis and will promptly notify Solo Health Collective of any changes.</p>
                                                            <p className="text-primary">Solo Health Collective may, at its sole discretion, decline to offer the Services for any reason, including but not limited to User’s failure to satisfactorily complete the Services enrollment process or Solo Health Collective’s inability to verify a valid credit or bank account of User’s.</p>
                                                        </li>
                                                        <li className="text-primary"><strong>Third-Party Services, Websites, and Resources.</strong> The Site and the Services may contain links to third-party websites and resources and allow Users to receive services from third-party partners of Solo Health Collective (“Third-Party Service”). If User elects to receive a Third-Party Service, User authorizes Solo Health Collective to submit to the applicable Third-Party Service any and all documents and information about User and User’s business that are necessary for provision of the Third-Party Service to User (collectively, the “Shared Information”). User understands that use of such Third-Party Services is at User’s own risk and that Solo Health Collective is not responsible for Third-Party Services or any material, information, or results made available through the third party. User also represents and warrants that User has all the rights in and to any Shared Information necessary to provide such Shared Information to Solo Health Collective and for Solo Health Collective to provide it to Third Party Services, and that Solo Health Collective’s use or disclosure of Shared Information as contemplated hereunder will not violate any rights of privacy or other proprietary rights, or any applicable local, state, or federal laws, regulations, orders, or rules.</li>
                                                        <li className="text-primary"><strong>User Account SMS/MMS Messages.</strong> Following User’s express written consent, Solo Health Collective may send User Short Message Service (“SMS”) or Multimedia Messaging Service (“MMS”) messages about activity in User’s Account and service updates, as well as SMS or MMS messages soliciting User’s feedback about the Services and User’s experience interacting with the Solo Health Collective Customer Care team. Standard message and data rates may apply.</li>
                                                        <li className="text-primary">
                                                            <p className="text-primary"><strong>Intellectual Property.</strong> The information and materials posted, generated, provided, or otherwise made available through the Services by Solo Health Collective, is the property of Solo Health Collective and its licensors (“Solo Health Collective Content”) and is protected by copyright, trademark, and other intellectual property laws. User Content and Solo Health Collective Content shall be collectively referred to herein as “Content.” Solo Health Collective and its licensors exclusively own all worldwide right, title, and interest in and to the Solo Health Collective Content, and also in and to the Site and the Services, including all associated intellectual property rights (“Solo Health Collective IP”).</p>
                                                            <p className="text-primary">User agrees not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Site, Services, or Solo Health Collective Content. Subject to User’s compliance with these T&Cs, Solo Health Collective grants User a limited, non-exclusive, non-transferable, non-sublicensable right to access, view, and download Solo Health Collective Content solely in connection with User’s permitted use of the Site and Services.</p>
                                                        </li>
                                                        <li className="text-primary"><strong>Solo Health Collective’s Rights to Monitor Users.</strong> Although Solo Health Collective is not obligated to monitor access to or use of the Site, Services, or Content, Solo Health Collective has the right to do so to operate the Site and Services, ensuring compliance with these T&Cs, and complying with applicable laws or other legal requirements. Solo Health Collective reserves the right, but is not obligated, to remove or disable access or suppress Content at any time and without notice, for any reason, including, but not limited to, if Solo Health Collective, at the company’s sole discretion, considers any content to be objectionable or in violation of these T&Cs.</li>
                                                        <li className="text-primary"><strong>E-Signatures.</strong> Solo Health Collective provides an electronic signature service that allows parties to sign documents electronically. Each time that User uses the electronic signature service, User is expressly (i) affirming that User is able to access and view the document User is electronically signing via the electronic signature service; (ii) consenting to conduct business electronically concerning the transaction contemplated by the document; and (iii) agreeing to the use of electronic signatures for the document. Solo Health Collective EXPRESSLY DISCLAIMS ANY RESPONSIBILITY FOR ENSURING THAT DOCUMENTS WHICH ARE ELECTRONICALLY SIGNED VIA THE ELECTRONIC SIGNATURE SERVICE ARE VALID AND ENFORCEABLE UNDER ANY APPLICABLE LOCAL, STATE, FEDERAL, OR INTERNATIONAL LAW OF ANY JURISDICTION.</li>
                                                        <li className="text-primary"><strong>Warranty Disclaimers.</strong> THE SITE, SERVICES, AND SOLO HEALTH COLLECTIVE CONTENT ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND MADE BY SOLO HEALTH COLLECTIVE. USER’S USE OF THE SITE, SERVICES, AND SOLO HEALTH COLLECTIVE CONTENT IS AT USER’S OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY LAW, SOLO HEALTH COLLECTIVE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, DATA LOSS, AND NON-INFRINGEMENT. FURTHERMORE, SOLO HEALTH COLLECTIVE MAKES NO WARRANTIES REGARDING THE ACCURACY, RELIABILITY, TIMELINESS, TRUTHFULNESS, COMPLETENESS, OR QUALITY OF ANY INFORMATION OR SOLO HEALTH COLLECTIVE CONTENT IN OR LINKED TO THE SERVICES.</li>
                                                        <li className="text-primary"><strong>No Professional Advice.</strong> Any information provided by Solo Health Collective via the Site or otherwise is meant for informational purposes only and should not be interpreted as professional advice. User should consult a professional who is trained or licensed in the relevant area if User needs such assistance.</li>
                                                        <li className="text-primary"><strong>Indemnity.</strong> User will indemnify and hold harmless Solo Health Collective and its officers, shareholders, employees, agents, directors, subsidiaries, affiliates, successors, assigns, service providers, and licensors (the “Indemnified Parties”), from and against any claims, disputes, demands, liabilities, damages, losses, costs, judgements, penalties, fines, and expenses (including, without limitation, reasonable legal and accounting fees) (collectively, the “Claims”), arising out of or in any way connected with (i) User’s access to or use of the Site, Services, or Content; (ii) User’s violation or alleged violation of these T&Cs; (iii) User’s violation or alleged violation of any third party right; (iv) User’s violation or alleged violation of any applicable law, rule, or regulation; (v) User’s negligence, fraudulent activity, or willful misconduct; (vi) the company’s or any other Indemnified Party’s use of or reliance on information or data furnished by User, an employee or independent contractor of User, User’s Account Administrator, or User’s Authorized Representative in providing the Services, or otherwise in connection with these T&Cs; (vii) actions or activities that Solo Health Collective or any other Indemnified Party undertakes in connection with the Services or these T&Cs at the direct request or instruction of anyone reasonably believed to be User, an Account Administrator, or an Authorized Representative (each such action or activity, a “Requested Action”); (viii) the company’s or any other Indemnified Party’s use of or reliance on information or data resulting from such Requested Actions; or (ix) User’s failure, or the failure of any Account Administrators or Authorized Representatives, to properly follow Solo Health Collective instructions with respect to the Services.</li>
                                                        <li className="text-primary">
                                                            <p className="text-primary"><strong>Limitation of Liability.</strong> Solo Health Collective is not responsible or liable for (i) User content or anyone’s reliance on User content; (ii) resulting errors or any consequences or claims directly or indirectly arising from resulting errors; (iii) any consequences or claims directly or indirectly resulting from User’s delay in providing, or User’s failure to provide, Solo Health Collective with information necessary for its provision of Services; (iv) User’s violation of any applicable law, rule, or regulation; (v) unauthorized third-party actions taken in User’s Account and any transactions, consequences, or claims arising therefrom; (vi) User’s negligence or any negligence of User’s account administrator or authorized representative; (vii) any circumstances or claims arising out of or related to a Third-Party Service’s use of User’s shared information; (viii) any requested actions, or any consequences or claims directly or indirectly resulting therefrom; or (ix) User’s failure, or the failure of any Account Administrators or Authorized Representatives, to properly follow Solo Health Collective instructions with respect to the Services.</p>
                                                            <p>IN NO EVENT WILL SOLO HEALTH COLLECTIVE, ITS OFFICERS, SHAREHOLDERS, EMPLOYEES, AGENTS, DIRECTORS, SUBSIDIARIES, AFFILIATES, SUCCESSORS, ASSIGNS, SERVICE PROVIDERS, OR LICENSORS BE LIABLE FOR (1) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES; (2) ANY LOSS OF USE, DATA, BUSINESS, OR PROFITS (WHETHER DIRECT OR INDIRECT), IN ALL CASES ARISING OUT OF THE USE OF OR INABILITY TO USE THE SITE, SERVICES, OR CONTENT, REGARDLESS OF LEGAL THEORY, WITHOUT REGARD TO WHETHER SOLO HEALTH COLLECTIVE HAS BEEN WARNED OF THE POSSIBILITY OF THOSE DAMAGES, AND EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
                                                        </li>
                                                        <li className="text-primary"><strong>Term; Termination; Suspension.</strong> The Services and these T&Cs will continue until terminated. Either Party may terminate the Services by giving the other party at least thirty (30) days’ prior notice. Solo Health Collective reserves the right to immediately suspend, restrict, or terminate User’s Account or access to the Site or Services, for any reason at any time including but not limited to: (i) User’s violation of these T&Cs; (ii) User’s failure to pay the required fees when due; or (iii) User’s breach of User’s contractual obligations hereunder. Upon termination of any Services, User’s right to access and use such Services will automatically terminate.</li>
                                                        <li className="text-primary"><strong>Changes to the T&Cs, Site, or Service.</strong> Solo Health Collective may modify the T&Cs at any time and at the company’s sole discretion. If Solo Health Collective makes a material changes to the T&Cs, Solo Health Collective will notify User via email. User’s continued use of the Site or Services after such modifications will constitute User’s acknowledgment of the modified T&Cs and agreement to be bound by its terms. Changes to the T&Cs are effective when they are posted. Because the Site and Services are evolving over time, Solo Health Collective may change or discontinue all or any part of the Site or Services at any time and without notice, at the company’s sole discretion and without any liability.</li>
                                                        <li className="text-primary"><strong>Governing Law; Waiver of Jury Trial.</strong> These T&Cs shall be interpreted and construed in accordance with the laws of the State of New York, without regard to the conflicts of lawsand principles thereof. USER HEREBY WAIVES, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY RIGHT USER MAY HAVE TO A TRIAL BY JURY IN ANY LEGAL PROCEEDING DIRECTLY OR INDIRECTLY ARISING OUT OF OR RELATING TO THESE T&CS OR THE SERVICES CONTEMPLATED HEREUNDER.</li>
                                                        <li className="text-primary"><strong>General.</strong> These T&Cs, including all applicable Service Terms, constitute the entire agreement between Solo Health Collective and User regarding the Site, Services, and Content and replace all prior understandings, communications, and agreements, oral or written, regarding this subject matter. These T&Cs may be modified only by a written amendment signed by the parties or as otherwise provided in Section 13. If any part of these T&Cs is deemed to be unenforceable or invalid, that section will be removed without affecting the remainder of the T&Cs and the remaining terms will be valid and enforceable.</li>
                                                        <li className="text-primary"><strong>Contact.</strong> Questions about these T&Cs may be sent to Solo Health Collective at <a href="mailto:support@hbgnow.com" className="highlight-text">support@hbgnow.com</a>.</li>
                                                    </ul>
                                                </div>
                                            </div>
      </section>
    </main>
  );
};

export default TermsAndConditions;